__default__:
    partition: "bch-compute"
    time: 60 # in min
    threads: 1
    mem: 2000
    output: output_%j.out ##CHANGE THIS. Log files for intermediate jobs, so a directory in scratch might work better.

# my_lianti_pileup_by_region:
#     partition: "medium"
